// <auto-generated />
namespace WebAppMedOffices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Columna_UserName_en_Medicos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Columna_UserName_en_Medicos));
        
        string IMigrationMetadata.Id
        {
            get { return "202010010243334_Columna_UserName_en_Medicos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
