// <auto-generated />
namespace WebAppMedOffices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agregar_Comentario_en_Turno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregar_Comentario_en_Turno));
        
        string IMigrationMetadata.Id
        {
            get { return "202010061814052_Agregar_Comentario_en_Turno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
