// <auto-generated />
namespace WebAppMedOffices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Eliminar_PacienteTurno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eliminar_PacienteTurno));
        
        string IMigrationMetadata.Id
        {
            get { return "202009292312023_Eliminar_PacienteTurno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
