// <auto-generated />
namespace WebAppMedOffices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Paciente_ObraSocial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Paciente_ObraSocial));
        
        string IMigrationMetadata.Id
        {
            get { return "202009300148295_Paciente_ObraSocial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
